---
- name: cleanup webserver
  hosts: all
  tasks:
  - name: removing package
    yum:
      name: httpd
      state: absent
  - name: clean up old files
    file:
      path: /var/www/html/index.html
      state: absent
